In [1]:

import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', None)

In [18]:
# Load CSV file
df = pd.read_csv("reviews2.csv")

#clean column name 
df.columns = df.columns.str.strip()

#rename column 
df.rename(columns={
    'Review': 'REVIEW',
    'Rate': 'RATE',
    'Summary': 'SUMMARY'
}, inplace=True)

#reorder column
df=df[['RATE','REVIEW','SUMMARY']]

df

      RATE               REVIEW                                                                                                                                                                                                                                                                   SUMMARY
0        5               super!                                                                                                                                                                            great cooler excellent air flow and for this price its so amazing and unbelievablejust love it
1        5              awesome                                                                                                                                                                                                                                     best budget 2 fit cooler nice cooling
2        3                 fair                                                                                                                                                                                                                        the quality is good but the power of air is decent
3        1      useless product                                                                                                                                                                                                                                         very bad product its a only a fan
4        3                 fair                                                                                                                                                                                                                                                             ok ok product
...    ...                  ...                                                                                                                                                                                                                                                                       ...
2494     5       simply awesome                                                                                                                                                                       superb and attractive item i like it so much i dont have any words to say go for it rit now friends
2495     5  best in the market!                                                                                                                                                            the headphones indeed are one of the best in the price range the bass is good and battery power is really cool
2496     4          pretty good                                                                                           i am in love with this headphone sound quality top notch build quality could be mote better but its not a big deal if we see price then its justified you can bilndly go for it
2497     4          pretty good                                                                    just good i buy for gaming use mostly for pubg bt little bit delay in sound and i will say wired headphones are the best for perfect audio quality its good if you just want listen songs not for pubg
2498     5     perfect product!  it is a very good looking product and you can feel that the plastic and the built look very premium but i dont feel there is any extra bass in that the sound quality is ok but nothing impressive but the money what you are paying you are getting a excellent product

[2499 rows x 3 columns]

In [19]:
#converting rate to sentiment 
def convert_sentiment(r):
    if r >= 4:
        return "Positive"
    elif r == 3:
        return "Neutral"
    else:
        return "Negative"

df['SENTIMENT'] = df['RATE'].apply(convert_sentiment)

df

      RATE               REVIEW                                                                                                                                                                                                                                                                   SUMMARY SENTIMENT
0        5               super!                                                                                                                                                                            great cooler excellent air flow and for this price its so amazing and unbelievablejust love it  Positive
1        5              awesome                                                                                                                                                                                                                                     best budget 2 fit cooler nice cooling  Positive
2        3                 fair                                                                                                                                                                                                                        the quality is good but the power of air is decent   Neutral
3        1      useless product                                                                                                                                                                                                                                         very bad product its a only a fan  Negative
4        3                 fair                                                                                                                                                                                                                                                             ok ok product   Neutral
...    ...                  ...                                                                                                                                                                                                                                                                       ...       ...
2494     5       simply awesome                                                                                                                                                                       superb and attractive item i like it so much i dont have any words to say go for it rit now friends  Positive
2495     5  best in the market!                                                                                                                                                            the headphones indeed are one of the best in the price range the bass is good and battery power is really cool  Positive
2496     4          pretty good                                                                                           i am in love with this headphone sound quality top notch build quality could be mote better but its not a big deal if we see price then its justified you can bilndly go for it  Positive
2497     4          pretty good                                                                    just good i buy for gaming use mostly for pubg bt little bit delay in sound and i will say wired headphones are the best for perfect audio quality its good if you just want listen songs not for pubg  Positive
2498     5     perfect product!  it is a very good looking product and you can feel that the plastic and the built look very premium but i dont feel there is any extra bass in that the sound quality is ok but nothing impressive but the money what you are paying you are getting a excellent product  Positive

[2499 rows x 4 columns]

In [20]:
# Data Preprocessing
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Download required data
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

# Initialize
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    
    # 1. Remove noise (special characters, numbers)
    text = re.sub('[^a-zA-Z]', ' ', str(text))
    
    # 2. Convert to lowercase
    text = text.lower()
    
    # 3. Split into words
    words = text.split()
    
    # 4. Remove stopwords + apply lemmatization
    words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]
    
    # 5. Join words back
    return " ".join(words)

# Apply preprocessing
df['clean_review'] = df['REVIEW'].apply(preprocess_text)
df['clean_summary'] = df['SUMMARY'].apply(preprocess_text)

# Drop original columns
df = df.drop(['REVIEW', 'SUMMARY'], axis=1)

df

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

      RATE SENTIMENT     clean_review                                                                                                                                         clean_summary
0        5  Positive            super                                                                                   great cooler excellent air flow price amazing unbelievablejust love
1        5  Positive          awesome                                                                                                                   best budget fit cooler nice cooling
2        3   Neutral             fair                                                                                                                         quality good power air decent
3        1  Negative  useless product                                                                                                                                       bad product fan
4        3   Neutral             fair                                                                                                                                         ok ok product
...    ...       ...              ...                                                                                                                                                   ...
2494     5  Positive   simply awesome                                                                                          superb attractive item like much dont word say go rit friend
2495     5  Positive      best market                                                                             headphone indeed one best price range bass good battery power really cool
2496     4  Positive      pretty good                                        love headphone sound quality top notch build quality could mote better big deal see price justified bilndly go
2497     4  Positive      pretty good                   good buy gaming use mostly pubg bt little bit delay sound say wired headphone best perfect audio quality good want listen song pubg
2498     5  Positive  perfect product  good looking product feel plastic built look premium dont feel extra bass sound quality ok nothing impressive money paying getting excellent product

[2499 rows x 4 columns]